### ISSUE TITLE
SetTarget without arguments

### ISSUE THREAD

**Issue by Shark-vil** [GammaWhiskey/BA2#5]
https://github.com/GammaWhiskey/BA2/blob/917c6265147a7bbe458c6ddc2ab01cb4bcf8f494/lua/entities/nb_ba2_infected.lua#L1496
--
Hello again. I saw that you have slightly modified the functions I proposed, however, it seems to me that "SetTarget" should accept arguments if you use this as a variant of calling "SetEnemy". Close this if I'm wrong. It’s already night, I’m not thinking well.

**Comment by GammaWhiskey** [comment]
WHOOPS I amended the commit wrong, good catch
